spring:
  application:
    name: lms
  datasource:
    url: jdbc:mysql://localhost:3306/minicampus
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zerobase

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
