spring:
  application:
    name: lms
  datasource:
    url: jdbc:mysql://localhost:3306/minicampus
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zerobase

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hojoon1011@bu.ac.kr
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true

logging:
  level:
    root: info

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
